### ISSUE TITLE
插件不可用

### ISSUE THREAD

**Issue by realfan** [akof1314/CoolFormat#14]
编译生成的插件，在Notepad++ unicode版本下不可用。需要unicode版本

**Comment by akof1314** [comment]
编译插件的话，请使用Visual Studio 2013编译，注意选择编译平台win32，都是Unicode版本的。

**Comment by akof1314** [comment]
应该是因为你用Qt Creator编译的dll，不是静态库版本，需要链接QT的一些库，你把
- libgcc_s_dw2-1.dll 
- libstdc++-6.dll
- libwinpthread-1.dll
  放到D:\Program Files\Notepad++ 安装目录即可。
