### ISSUE TITLE
导出配置失败

### ISSUE THREAD

**Issue by mzhboy** [akof1314/CoolFormat#16]
3.4版本，导出配置后在目标文件夹下面没有配置文件，Win8.1 x64

**Comment by mzhboy** [comment]
原来需要导入以前的配置再重新导出，没有改变默认配置是不能导出的

**Comment by akof1314** [comment]
@mzhboy 谢谢提醒，我标记下之后处理。

**Comment by mzhboy** [comment]
建议启动时默认载入同目录下的配置文件

2015-06-23 14:56 GMT+08:00 WuHuan notifications@github.com:
