### ISSUE TITLE
deletes lines/whole text for non-supported syntax

### ISSUE THREAD

**Issue by nazikus** [akof1314/CoolFormat#18]
If I try to use CoolFormat for non-supported syntax (e.g., python, batch), it deletes a line (Selected Format) or the whole file content (Quick Format)

**Comment by akof1314** [comment]
Yes,do not try to use for non-supported syntax

**Comment by nazikus** [comment]
it would be good to auto-disable CoolFormat for non-supported syntaxes. Thanks

**Comment by akof1314** [comment]
The CoolFormat.exe application or the Plugins?eg. Visual Studio 2013, Notepad++?

**Comment by nazikus** [comment]
oh, sorry. I'm using sublime text and was thinking from its perspective. So if I use shortcut for CoolFormat `Ctrl+Alt+Shift+S`, it just deletes content for non-supported syntax, which is quite undesirable behavior.

**Comment by akof1314** [comment]
OK. I will fix it later.
