### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by 461353349** [akof1314/CoolFormat#33]
1）既然作为开源软件，为什么不使用Qt+Ribbon？
2）项目中有Pro文件，使用Qt打开后发现里面只能生成lib，而没有app，即没有可执行程序生成。

**Comment by akof1314** [comment]
1) 没有精力再在使用Qt构建一个界面程序了
2) 故提供Pro文件，生成lib让第三方来调用

**Comment by 461353349** [comment]
非常感谢您的答复。
我使用Qt打开pro文件，进行编译时提示两个文件找不到，不知道如何解决？
: warning: Failure to find: localize.c
: warning: Failure to find: win32tc.c

**Comment by akof1314** [comment]
不要使用develop分支，使用tag分支

**Comment by 461353349** [comment]
使用Tag分支，编译好了。
如果使用Pro文件进行编译，会报三个错误：“无法解析的外部符号 RegQueryValueEx、RegCloseKey、RegOpenKeyEx”，解决办法是在pro中增加一行
LIBS += -lAdvAPI32
前提是系统中有这个对应的文件
BTW：写中文感觉还是很好的
