### ISSUE TITLE
Format on Save

### ISSUE THREAD

**Issue by hasanbayatme** [akof1314/CoolFormat#34]
How to make it format on save?

**Comment by akof1314** [comment]
Not supported now

**Comment by hasanbayatme** [comment]
Please mark it as feature request.
also try to add it. because it is a powerful formatter.
Thanks.

**Comment by akof1314** [comment]
It can be used as a plugin for other editors, so you can  format on save in other editors.

**Comment by hasanbayatme** [comment]
How do i do it in sublime text?

**Comment by akof1314** [comment]
Sublime-CoolFormat  https://github.com/akof1314/Sublime-CoolFormat

**Comment by hasanbayatme** [comment]
Let me move the issue to there.
Closed, Moved. [#10](https://github.com/akof1314/Sublime-CoolFormat/issues/10)
