### ISSUE TITLE
源码文件缺少：tidyplatform.h、tidybuffio.h

### ISSUE THREAD

**Issue by MyTkme** [akof1314/CoolFormat#39]
本来打算 学习一下C++，在本地编译你的源码，结果 报错，tidyplatform.h、tidybuffio.h文件不存在，跑不起来，楼主有时间，提交一下

**Comment by akof1314** [comment]
@MyTkme 不要用develop分支，用tag分支

**Comment by MyTkme** [comment]
@akof1314 
Tags 3.4缺少：BCGCBProInc.h，
Visual Studio 2015 还是编译不通过
![default](https://user-images.githubusercontent.com/33886182/33197285-6d78e9ce-d11f-11e7-8ac0-568fdc425401.png)

**Comment by akof1314** [comment]
这个是带界面的工程，需要自己去下载第三方库。可以使用其他工程，编译dll的方式。
